// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/rating/rating.proto

package rating

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRatingByBuildIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=buildId,proto3" json:"buildId,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingByBuildIdRequest) Reset() {
	*x = CreateRatingByBuildIdRequest{}
	mi := &file_api_proto_rating_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingByBuildIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingByBuildIdRequest) ProtoMessage() {}

func (x *CreateRatingByBuildIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rating_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingByBuildIdRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingByBuildIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rating_rating_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRatingByBuildIdRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateRatingByBuildIdRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CreateRatingByBuildIdRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateRatingByBuildIdRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateRatingByBuildIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingByBuildIdResponse) Reset() {
	*x = CreateRatingByBuildIdResponse{}
	mi := &file_api_proto_rating_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingByBuildIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingByBuildIdResponse) ProtoMessage() {}

func (x *CreateRatingByBuildIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rating_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingByBuildIdResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingByBuildIdResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rating_rating_proto_rawDescGZIP(), []int{1}
}

var File_api_proto_rating_rating_proto protoreflect.FileDescriptor

const file_api_proto_rating_rating_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/rating/rating.proto\x12\x06rating\"\x86\x01\n" +
	"\x1cCreateRatingByBuildIdRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\tR\bmemberId\x12\x18\n" +
	"\abuildId\x18\x02 \x01(\tR\abuildId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\"\x1f\n" +
	"\x1dCreateRatingByBuildIdResponse2w\n" +
	"\rRatingService\x12f\n" +
	"\x15CreateRatingByBuildId\x12$.rating.CreateRatingByBuildIdRequest\x1a%.rating.CreateRatingByBuildIdResponse\"\x00BPZNgithub.com/darkphotonKN/community-builds-microservices/common/api/proto/ratingb\x06proto3"

var (
	file_api_proto_rating_rating_proto_rawDescOnce sync.Once
	file_api_proto_rating_rating_proto_rawDescData []byte
)

func file_api_proto_rating_rating_proto_rawDescGZIP() []byte {
	file_api_proto_rating_rating_proto_rawDescOnce.Do(func() {
		file_api_proto_rating_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rating_rating_proto_rawDesc), len(file_api_proto_rating_rating_proto_rawDesc)))
	})
	return file_api_proto_rating_rating_proto_rawDescData
}

var file_api_proto_rating_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_rating_rating_proto_goTypes = []any{
	(*CreateRatingByBuildIdRequest)(nil),  // 0: rating.CreateRatingByBuildIdRequest
	(*CreateRatingByBuildIdResponse)(nil), // 1: rating.CreateRatingByBuildIdResponse
}
var file_api_proto_rating_rating_proto_depIdxs = []int32{
	0, // 0: rating.RatingService.CreateRatingByBuildId:input_type -> rating.CreateRatingByBuildIdRequest
	1, // 1: rating.RatingService.CreateRatingByBuildId:output_type -> rating.CreateRatingByBuildIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_rating_rating_proto_init() }
func file_api_proto_rating_rating_proto_init() {
	if File_api_proto_rating_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rating_rating_proto_rawDesc), len(file_api_proto_rating_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rating_rating_proto_goTypes,
		DependencyIndexes: file_api_proto_rating_rating_proto_depIdxs,
		MessageInfos:      file_api_proto_rating_rating_proto_msgTypes,
	}.Build()
	File_api_proto_rating_rating_proto = out.File
	file_api_proto_rating_rating_proto_goTypes = nil
	file_api_proto_rating_rating_proto_depIdxs = nil
}
