// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: api/proto/item/item.proto

package item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	MemberId    string                 `protobuf:"bytes,2,opt,name=memberId,proto3" json:"memberId,omitempty"`
	BaseItemId  string                 `protobuf:"bytes,3,opt,name=baseItemId,proto3" json:"baseItemId,omitempty"`
	ImageUrl    string                 `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Category    string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Class       string                 `protobuf:"bytes,6,opt,name=class,proto3" json:"class,omitempty"`
	Name        string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Type        string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Description string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	UniqueItem  bool                   `protobuf:"varint,10,opt,name=uniqueItem,proto3" json:"uniqueItem,omitempty"`
	Slot        string                 `protobuf:"bytes,11,opt,name=slot,proto3" json:"slot,omitempty"`
	// armor
	RequiredLevel        *string `protobuf:"bytes,12,opt,name=requiredLevel,proto3,oneof" json:"requiredLevel,omitempty"`
	RequiredStrength     *string `protobuf:"bytes,13,opt,name=requiredStrength,proto3,oneof" json:"requiredStrength,omitempty"`
	RequiredDexterity    *string `protobuf:"bytes,14,opt,name=requiredDexterity,proto3,oneof" json:"requiredDexterity,omitempty"`
	RequiredIntelligence *string `protobuf:"bytes,15,opt,name=requiredIntelligence,proto3,oneof" json:"requiredIntelligence,omitempty"`
	// armor
	Armour       *string `protobuf:"bytes,16,opt,name=armour,proto3,oneof" json:"armour,omitempty"`
	EnergyShield *string `protobuf:"bytes,17,opt,name=energyShield,proto3,oneof" json:"energyShield,omitempty"`
	Evasion      *string `protobuf:"bytes,18,opt,name=evasion,proto3,oneof" json:"evasion,omitempty"`
	Block        *string `protobuf:"bytes,19,opt,name=block,proto3,oneof" json:"block,omitempty"`
	Ward         *string `protobuf:"bytes,20,opt,name=ward,proto3,oneof" json:"ward,omitempty"`
	// weapon
	Damage *string `protobuf:"bytes,21,opt,name=damage,proto3,oneof" json:"damage,omitempty"`
	APS    *string `protobuf:"bytes,22,opt,name=APS,proto3,oneof" json:"APS,omitempty"`
	Crit   *string `protobuf:"bytes,23,opt,name=crit,proto3,oneof" json:"crit,omitempty"`
	PDPS   *string `protobuf:"bytes,24,opt,name=PDPS,proto3,oneof" json:"PDPS,omitempty"`
	EDPS   *string `protobuf:"bytes,25,opt,name=EDPS,proto3,oneof" json:"EDPS,omitempty"`
	DPS    *string `protobuf:"bytes,26,opt,name=DPS,proto3,oneof" json:"DPS,omitempty"`
	// poison
	Life          *string  `protobuf:"bytes,27,opt,name=life,proto3,oneof" json:"life,omitempty"`
	Mana          *string  `protobuf:"bytes,28,opt,name=mana,proto3,oneof" json:"mana,omitempty"`
	Duration      *string  `protobuf:"bytes,29,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Usage         *string  `protobuf:"bytes,30,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	Capacity      *string  `protobuf:"bytes,31,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	Additional    *string  `protobuf:"bytes,32,opt,name=additional,proto3,oneof" json:"additional,omitempty"`
	Implicit      []string `protobuf:"bytes,33,rep,name=implicit,proto3" json:"implicit,omitempty"`
	Stats         []string `protobuf:"bytes,34,rep,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *string  `protobuf:"bytes,36,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	UpdatedAt     *string  `protobuf:"bytes,37,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Item) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Item) GetBaseItemId() string {
	if x != nil {
		return x.BaseItemId
	}
	return ""
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetUniqueItem() bool {
	if x != nil {
		return x.UniqueItem
	}
	return false
}

func (x *Item) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Item) GetRequiredLevel() string {
	if x != nil && x.RequiredLevel != nil {
		return *x.RequiredLevel
	}
	return ""
}

func (x *Item) GetRequiredStrength() string {
	if x != nil && x.RequiredStrength != nil {
		return *x.RequiredStrength
	}
	return ""
}

func (x *Item) GetRequiredDexterity() string {
	if x != nil && x.RequiredDexterity != nil {
		return *x.RequiredDexterity
	}
	return ""
}

func (x *Item) GetRequiredIntelligence() string {
	if x != nil && x.RequiredIntelligence != nil {
		return *x.RequiredIntelligence
	}
	return ""
}

func (x *Item) GetArmour() string {
	if x != nil && x.Armour != nil {
		return *x.Armour
	}
	return ""
}

func (x *Item) GetEnergyShield() string {
	if x != nil && x.EnergyShield != nil {
		return *x.EnergyShield
	}
	return ""
}

func (x *Item) GetEvasion() string {
	if x != nil && x.Evasion != nil {
		return *x.Evasion
	}
	return ""
}

func (x *Item) GetBlock() string {
	if x != nil && x.Block != nil {
		return *x.Block
	}
	return ""
}

func (x *Item) GetWard() string {
	if x != nil && x.Ward != nil {
		return *x.Ward
	}
	return ""
}

func (x *Item) GetDamage() string {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return ""
}

func (x *Item) GetAPS() string {
	if x != nil && x.APS != nil {
		return *x.APS
	}
	return ""
}

func (x *Item) GetCrit() string {
	if x != nil && x.Crit != nil {
		return *x.Crit
	}
	return ""
}

func (x *Item) GetPDPS() string {
	if x != nil && x.PDPS != nil {
		return *x.PDPS
	}
	return ""
}

func (x *Item) GetEDPS() string {
	if x != nil && x.EDPS != nil {
		return *x.EDPS
	}
	return ""
}

func (x *Item) GetDPS() string {
	if x != nil && x.DPS != nil {
		return *x.DPS
	}
	return ""
}

func (x *Item) GetLife() string {
	if x != nil && x.Life != nil {
		return *x.Life
	}
	return ""
}

func (x *Item) GetMana() string {
	if x != nil && x.Mana != nil {
		return *x.Mana
	}
	return ""
}

func (x *Item) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *Item) GetUsage() string {
	if x != nil && x.Usage != nil {
		return *x.Usage
	}
	return ""
}

func (x *Item) GetCapacity() string {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return ""
}

func (x *Item) GetAdditional() string {
	if x != nil && x.Additional != nil {
		return *x.Additional
	}
	return ""
}

func (x *Item) GetImplicit() []string {
	if x != nil {
		return x.Implicit
	}
	return nil
}

func (x *Item) GetStats() []string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Item) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *Item) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type BaseItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl             string                 `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Category             string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Class                string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	EquipType            string                 `protobuf:"bytes,7,opt,name=equipType,proto3" json:"equipType,omitempty"`
	IsTwoHands           bool                   `protobuf:"varint,8,opt,name=isTwoHands,proto3" json:"isTwoHands,omitempty"`
	Slot                 string                 `protobuf:"bytes,9,opt,name=slot,proto3" json:"slot,omitempty"`
	RequiredLevel        string                 `protobuf:"bytes,10,opt,name=requiredLevel,proto3" json:"requiredLevel,omitempty"`
	RequiredStrength     string                 `protobuf:"bytes,11,opt,name=requiredStrength,proto3" json:"requiredStrength,omitempty"`
	RequiredDexterity    string                 `protobuf:"bytes,12,opt,name=requiredDexterity,proto3" json:"requiredDexterity,omitempty"`
	RequiredIntelligence string                 `protobuf:"bytes,13,opt,name=requiredIntelligence,proto3" json:"requiredIntelligence,omitempty"`
	Damage               string                 `protobuf:"bytes,14,opt,name=damage,proto3" json:"damage,omitempty"`
	Aps                  string                 `protobuf:"bytes,15,opt,name=aps,proto3" json:"aps,omitempty"`
	Crit                 string                 `protobuf:"bytes,16,opt,name=crit,proto3" json:"crit,omitempty"`
	DPS                  string                 `protobuf:"bytes,17,opt,name=DPS,proto3" json:"DPS,omitempty"`
	Armour               string                 `protobuf:"bytes,18,opt,name=armour,proto3" json:"armour,omitempty"`
	Evasion              string                 `protobuf:"bytes,19,opt,name=evasion,proto3" json:"evasion,omitempty"`
	EnergyShield         string                 `protobuf:"bytes,20,opt,name=energyShield,proto3" json:"energyShield,omitempty"`
	Ward                 string                 `protobuf:"bytes,21,opt,name=ward,proto3" json:"ward,omitempty"`
	Implicit             []string               `protobuf:"bytes,22,rep,name=implicit,proto3" json:"implicit,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,23,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,24,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BaseItem) Reset() {
	*x = BaseItem{}
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseItem) ProtoMessage() {}

func (x *BaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseItem.ProtoReflect.Descriptor instead.
func (*BaseItem) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *BaseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BaseItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BaseItem) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *BaseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseItem) GetEquipType() string {
	if x != nil {
		return x.EquipType
	}
	return ""
}

func (x *BaseItem) GetIsTwoHands() bool {
	if x != nil {
		return x.IsTwoHands
	}
	return false
}

func (x *BaseItem) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *BaseItem) GetRequiredLevel() string {
	if x != nil {
		return x.RequiredLevel
	}
	return ""
}

func (x *BaseItem) GetRequiredStrength() string {
	if x != nil {
		return x.RequiredStrength
	}
	return ""
}

func (x *BaseItem) GetRequiredDexterity() string {
	if x != nil {
		return x.RequiredDexterity
	}
	return ""
}

func (x *BaseItem) GetRequiredIntelligence() string {
	if x != nil {
		return x.RequiredIntelligence
	}
	return ""
}

func (x *BaseItem) GetDamage() string {
	if x != nil {
		return x.Damage
	}
	return ""
}

func (x *BaseItem) GetAps() string {
	if x != nil {
		return x.Aps
	}
	return ""
}

func (x *BaseItem) GetCrit() string {
	if x != nil {
		return x.Crit
	}
	return ""
}

func (x *BaseItem) GetDPS() string {
	if x != nil {
		return x.DPS
	}
	return ""
}

func (x *BaseItem) GetArmour() string {
	if x != nil {
		return x.Armour
	}
	return ""
}

func (x *BaseItem) GetEvasion() string {
	if x != nil {
		return x.Evasion
	}
	return ""
}

func (x *BaseItem) GetEnergyShield() string {
	if x != nil {
		return x.EnergyShield
	}
	return ""
}

func (x *BaseItem) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *BaseItem) GetImplicit() []string {
	if x != nil {
		return x.Implicit
	}
	return nil
}

func (x *BaseItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *BaseItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ItemMod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Affix         string                 `protobuf:"bytes,2,opt,name=affix,proto3" json:"affix,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Stat          string                 `protobuf:"bytes,5,opt,name=stat,proto3" json:"stat,omitempty"`
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMod) Reset() {
	*x = ItemMod{}
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMod) ProtoMessage() {}

func (x *ItemMod) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMod.ProtoReflect.Descriptor instead.
func (*ItemMod) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemMod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemMod) GetAffix() string {
	if x != nil {
		return x.Affix
	}
	return ""
}

func (x *ItemMod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemMod) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ItemMod) GetStat() string {
	if x != nil {
		return x.Stat
	}
	return ""
}

func (x *ItemMod) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *ItemMod) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ItemMod) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Slot          string                 `protobuf:"bytes,7,opt,name=slot,proto3" json:"slot,omitempty"` // repeated Item items = 6;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *CreateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *CreateItemRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemsRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // array of items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GenerateUniqueItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUniqueItemsResponse) Reset() {
	*x = GenerateUniqueItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUniqueItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUniqueItemsResponse) ProtoMessage() {}

func (x *GenerateUniqueItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUniqueItemsResponse.ProtoReflect.Descriptor instead.
func (*GenerateUniqueItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateUniqueItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *UpdateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRareItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BaseItemId    string                 `protobuf:"bytes,2,opt,name=baseItemId,proto3" json:"baseItemId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Stats         []string               `protobuf:"bytes,5,rep,name=stats,proto3" json:"stats,omitempty"`
	ToList        bool                   `protobuf:"varint,6,opt,name=toList,proto3" json:"toList,omitempty"` // whether to add the item to the user's item list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRareItemRequest) Reset() {
	*x = CreateRareItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRareItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRareItemRequest) ProtoMessage() {}

func (x *CreateRareItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRareItemRequest.ProtoReflect.Descriptor instead.
func (*CreateRareItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRareItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRareItemRequest) GetBaseItemId() string {
	if x != nil {
		return x.BaseItemId
	}
	return ""
}

func (x *CreateRareItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRareItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateRareItemRequest) GetStats() []string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *CreateRareItemRequest) GetToList() bool {
	if x != nil {
		return x.ToList
	}
	return false
}

type CreateRareItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRareItemResponse) Reset() {
	*x = CreateRareItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRareItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRareItemResponse) ProtoMessage() {}

func (x *CreateRareItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRareItemResponse.ProtoReflect.Descriptor instead.
func (*CreateRareItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRareItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBaseItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseItemsRequest) Reset() {
	*x = GetBaseItemsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseItemsRequest) ProtoMessage() {}

func (x *GetBaseItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseItemsRequest.ProtoReflect.Descriptor instead.
func (*GetBaseItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{12}
}

type GetBaseItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseItems     []*BaseItem            `protobuf:"bytes,1,rep,name=baseItems,proto3" json:"baseItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseItemsResponse) Reset() {
	*x = GetBaseItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseItemsResponse) ProtoMessage() {}

func (x *GetBaseItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseItemsResponse.ProtoReflect.Descriptor instead.
func (*GetBaseItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{13}
}

func (x *GetBaseItemsResponse) GetBaseItems() []*BaseItem {
	if x != nil {
		return x.BaseItems
	}
	return nil
}

type GetItemModsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemModsRequest) Reset() {
	*x = GetItemModsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemModsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemModsRequest) ProtoMessage() {}

func (x *GetItemModsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemModsRequest.ProtoReflect.Descriptor instead.
func (*GetItemModsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{14}
}

type GetItemModsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemMods      []*ItemMod             `protobuf:"bytes,1,rep,name=itemMods,proto3" json:"itemMods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemModsResponse) Reset() {
	*x = GetItemModsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemModsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemModsResponse) ProtoMessage() {}

func (x *GetItemModsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemModsResponse.ProtoReflect.Descriptor instead.
func (*GetItemModsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{15}
}

func (x *GetItemModsResponse) GetItemMods() []*ItemMod {
	if x != nil {
		return x.ItemMods
	}
	return nil
}

type GetMemberRareItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRareItemsRequest) Reset() {
	*x = GetMemberRareItemsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRareItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRareItemsRequest) ProtoMessage() {}

func (x *GetMemberRareItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRareItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRareItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{16}
}

func (x *GetMemberRareItemsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type GetMemberRareItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRareItemsResponse) Reset() {
	*x = GetMemberRareItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRareItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRareItemsResponse) ProtoMessage() {}

func (x *GetMemberRareItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRareItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMemberRareItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{17}
}

func (x *GetMemberRareItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_item_item_proto protoreflect.FileDescriptor

const file_api_proto_item_item_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/item/item.proto\x12\bitemgrpc\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\n" +
	"\n" +
	"\x04Item\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1a\n" +
	"\bmemberId\x18\x02 \x01(\tR\bmemberId\x12\x1e\n" +
	"\n" +
	"baseItemId\x18\x03 \x01(\tR\n" +
	"baseItemId\x12\x1a\n" +
	"\bimageUrl\x18\x04 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x06 \x01(\tR\x05class\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"uniqueItem\x18\n" +
	" \x01(\bR\n" +
	"uniqueItem\x12\x12\n" +
	"\x04slot\x18\v \x01(\tR\x04slot\x12)\n" +
	"\rrequiredLevel\x18\f \x01(\tH\x01R\rrequiredLevel\x88\x01\x01\x12/\n" +
	"\x10requiredStrength\x18\r \x01(\tH\x02R\x10requiredStrength\x88\x01\x01\x121\n" +
	"\x11requiredDexterity\x18\x0e \x01(\tH\x03R\x11requiredDexterity\x88\x01\x01\x127\n" +
	"\x14requiredIntelligence\x18\x0f \x01(\tH\x04R\x14requiredIntelligence\x88\x01\x01\x12\x1b\n" +
	"\x06armour\x18\x10 \x01(\tH\x05R\x06armour\x88\x01\x01\x12'\n" +
	"\fenergyShield\x18\x11 \x01(\tH\x06R\fenergyShield\x88\x01\x01\x12\x1d\n" +
	"\aevasion\x18\x12 \x01(\tH\aR\aevasion\x88\x01\x01\x12\x19\n" +
	"\x05block\x18\x13 \x01(\tH\bR\x05block\x88\x01\x01\x12\x17\n" +
	"\x04ward\x18\x14 \x01(\tH\tR\x04ward\x88\x01\x01\x12\x1b\n" +
	"\x06damage\x18\x15 \x01(\tH\n" +
	"R\x06damage\x88\x01\x01\x12\x15\n" +
	"\x03APS\x18\x16 \x01(\tH\vR\x03APS\x88\x01\x01\x12\x17\n" +
	"\x04crit\x18\x17 \x01(\tH\fR\x04crit\x88\x01\x01\x12\x17\n" +
	"\x04PDPS\x18\x18 \x01(\tH\rR\x04PDPS\x88\x01\x01\x12\x17\n" +
	"\x04EDPS\x18\x19 \x01(\tH\x0eR\x04EDPS\x88\x01\x01\x12\x15\n" +
	"\x03DPS\x18\x1a \x01(\tH\x0fR\x03DPS\x88\x01\x01\x12\x17\n" +
	"\x04life\x18\x1b \x01(\tH\x10R\x04life\x88\x01\x01\x12\x17\n" +
	"\x04mana\x18\x1c \x01(\tH\x11R\x04mana\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x1d \x01(\tH\x12R\bduration\x88\x01\x01\x12\x19\n" +
	"\x05usage\x18\x1e \x01(\tH\x13R\x05usage\x88\x01\x01\x12\x1f\n" +
	"\bcapacity\x18\x1f \x01(\tH\x14R\bcapacity\x88\x01\x01\x12#\n" +
	"\n" +
	"additional\x18  \x01(\tH\x15R\n" +
	"additional\x88\x01\x01\x12\x1a\n" +
	"\bimplicit\x18! \x03(\tR\bimplicit\x12\x14\n" +
	"\x05stats\x18\" \x03(\tR\x05stats\x12!\n" +
	"\tcreatedAt\x18$ \x01(\tH\x16R\tcreatedAt\x88\x01\x01\x12!\n" +
	"\tupdatedAt\x18% \x01(\tH\x17R\tupdatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_requiredLevelB\x13\n" +
	"\x11_requiredStrengthB\x14\n" +
	"\x12_requiredDexterityB\x17\n" +
	"\x15_requiredIntelligenceB\t\n" +
	"\a_armourB\x0f\n" +
	"\r_energyShieldB\n" +
	"\n" +
	"\b_evasionB\b\n" +
	"\x06_blockB\a\n" +
	"\x05_wardB\t\n" +
	"\a_damageB\x06\n" +
	"\x04_APSB\a\n" +
	"\x05_critB\a\n" +
	"\x05_PDPSB\a\n" +
	"\x05_EDPSB\x06\n" +
	"\x04_DPSB\a\n" +
	"\x05_lifeB\a\n" +
	"\x05_manaB\v\n" +
	"\t_durationB\b\n" +
	"\x06_usageB\v\n" +
	"\t_capacityB\r\n" +
	"\v_additionalB\f\n" +
	"\n" +
	"_createdAtB\f\n" +
	"\n" +
	"_updatedAt\"\xa8\x05\n" +
	"\bBaseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bimageUrl\x18\x02 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1c\n" +
	"\tequipType\x18\a \x01(\tR\tequipType\x12\x1e\n" +
	"\n" +
	"isTwoHands\x18\b \x01(\bR\n" +
	"isTwoHands\x12\x12\n" +
	"\x04slot\x18\t \x01(\tR\x04slot\x12$\n" +
	"\rrequiredLevel\x18\n" +
	" \x01(\tR\rrequiredLevel\x12*\n" +
	"\x10requiredStrength\x18\v \x01(\tR\x10requiredStrength\x12,\n" +
	"\x11requiredDexterity\x18\f \x01(\tR\x11requiredDexterity\x122\n" +
	"\x14requiredIntelligence\x18\r \x01(\tR\x14requiredIntelligence\x12\x16\n" +
	"\x06damage\x18\x0e \x01(\tR\x06damage\x12\x10\n" +
	"\x03aps\x18\x0f \x01(\tR\x03aps\x12\x12\n" +
	"\x04crit\x18\x10 \x01(\tR\x04crit\x12\x10\n" +
	"\x03DPS\x18\x11 \x01(\tR\x03DPS\x12\x16\n" +
	"\x06armour\x18\x12 \x01(\tR\x06armour\x12\x18\n" +
	"\aevasion\x18\x13 \x01(\tR\aevasion\x12\"\n" +
	"\fenergyShield\x18\x14 \x01(\tR\fenergyShield\x12\x12\n" +
	"\x04ward\x18\x15 \x01(\tR\x04ward\x12\x1a\n" +
	"\bimplicit\x18\x16 \x03(\tR\bimplicit\x12\x1c\n" +
	"\tupdatedAt\x18\x17 \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tcreatedAt\x18\x18 \x01(\tR\tcreatedAt\"\xbd\x01\n" +
	"\aItemMod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05affix\x18\x02 \x01(\tR\x05affix\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x12\n" +
	"\x04stat\x18\x05 \x01(\tR\x04stat\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\xad\x01\n" +
	"\x11CreateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\x12\x12\n" +
	"\x04slot\x18\a \x01(\tR\x04slot\".\n" +
	"\x12CreateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x0fGetItemsRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"8\n" +
	"\x10GetItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.itemgrpc.ItemR\x05items\"7\n" +
	"\x1bGenerateUniqueItemsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x99\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\".\n" +
	"\x12UpdateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x15CreateRareItemRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"baseItemId\x18\x02 \x01(\tR\n" +
	"baseItemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x14\n" +
	"\x05stats\x18\x05 \x03(\tR\x05stats\x12\x16\n" +
	"\x06toList\x18\x06 \x01(\bR\x06toList\"2\n" +
	"\x16CreateRareItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13GetBaseItemsRequest\"H\n" +
	"\x14GetBaseItemsResponse\x120\n" +
	"\tbaseItems\x18\x01 \x03(\v2\x12.itemgrpc.BaseItemR\tbaseItems\"\x14\n" +
	"\x12GetItemModsRequest\"D\n" +
	"\x13GetItemModsResponse\x12-\n" +
	"\bitemMods\x18\x01 \x03(\v2\x11.itemgrpc.ItemModR\bitemMods\"7\n" +
	"\x19GetMemberRareItemsRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\tR\bmemberId\"B\n" +
	"\x1aGetMemberRareItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.itemgrpc.ItemR\x05items2\x99\x05\n" +
	"\vItemService\x12I\n" +
	"\n" +
	"CreateItem\x12\x1b.itemgrpc.CreateItemRequest\x1a\x1c.itemgrpc.CreateItemResponse\"\x00\x12C\n" +
	"\bGetItems\x12\x19.itemgrpc.GetItemsRequest\x1a\x1a.itemgrpc.GetItemsResponse\"\x00\x12V\n" +
	"\x13GenerateUniqueItems\x12\x16.google.protobuf.Empty\x1a%.itemgrpc.GenerateUniqueItemsResponse\"\x00\x12I\n" +
	"\n" +
	"UpdateItem\x12\x1b.itemgrpc.UpdateItemRequest\x1a\x1c.itemgrpc.UpdateItemResponse\"\x00\x12U\n" +
	"\x0eCreateRareItem\x12\x1f.itemgrpc.CreateRareItemRequest\x1a .itemgrpc.CreateRareItemResponse\"\x00\x12O\n" +
	"\fGetBaseItems\x12\x1d.itemgrpc.GetBaseItemsRequest\x1a\x1e.itemgrpc.GetBaseItemsResponse\"\x00\x12L\n" +
	"\vGetItemMods\x12\x1c.itemgrpc.GetItemModsRequest\x1a\x1d.itemgrpc.GetItemModsResponse\"\x00\x12a\n" +
	"\x12GetMemberRareItems\x12#.itemgrpc.GetMemberRareItemsRequest\x1a$.itemgrpc.GetMemberRareItemsResponse\"\x00BMZKgithub.com/darkphotonKN/community-builds-microservice/common/api/proto/itemb\x06proto3"

var (
	file_api_proto_item_item_proto_rawDescOnce sync.Once
	file_api_proto_item_item_proto_rawDescData []byte
)

func file_api_proto_item_item_proto_rawDescGZIP() []byte {
	file_api_proto_item_item_proto_rawDescOnce.Do(func() {
		file_api_proto_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)))
	})
	return file_api_proto_item_item_proto_rawDescData
}

var file_api_proto_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_item_item_proto_goTypes = []any{
	(*Item)(nil),                        // 0: itemgrpc.Item
	(*BaseItem)(nil),                    // 1: itemgrpc.BaseItem
	(*ItemMod)(nil),                     // 2: itemgrpc.ItemMod
	(*CreateItemRequest)(nil),           // 3: itemgrpc.CreateItemRequest
	(*CreateItemResponse)(nil),          // 4: itemgrpc.CreateItemResponse
	(*GetItemsRequest)(nil),             // 5: itemgrpc.GetItemsRequest
	(*GetItemsResponse)(nil),            // 6: itemgrpc.GetItemsResponse
	(*GenerateUniqueItemsResponse)(nil), // 7: itemgrpc.GenerateUniqueItemsResponse
	(*UpdateItemRequest)(nil),           // 8: itemgrpc.UpdateItemRequest
	(*UpdateItemResponse)(nil),          // 9: itemgrpc.UpdateItemResponse
	(*CreateRareItemRequest)(nil),       // 10: itemgrpc.CreateRareItemRequest
	(*CreateRareItemResponse)(nil),      // 11: itemgrpc.CreateRareItemResponse
	(*GetBaseItemsRequest)(nil),         // 12: itemgrpc.GetBaseItemsRequest
	(*GetBaseItemsResponse)(nil),        // 13: itemgrpc.GetBaseItemsResponse
	(*GetItemModsRequest)(nil),          // 14: itemgrpc.GetItemModsRequest
	(*GetItemModsResponse)(nil),         // 15: itemgrpc.GetItemModsResponse
	(*GetMemberRareItemsRequest)(nil),   // 16: itemgrpc.GetMemberRareItemsRequest
	(*GetMemberRareItemsResponse)(nil),  // 17: itemgrpc.GetMemberRareItemsResponse
	(*emptypb.Empty)(nil),               // 18: google.protobuf.Empty
}
var file_api_proto_item_item_proto_depIdxs = []int32{
	0,  // 0: itemgrpc.GetItemsResponse.items:type_name -> itemgrpc.Item
	1,  // 1: itemgrpc.GetBaseItemsResponse.baseItems:type_name -> itemgrpc.BaseItem
	2,  // 2: itemgrpc.GetItemModsResponse.itemMods:type_name -> itemgrpc.ItemMod
	0,  // 3: itemgrpc.GetMemberRareItemsResponse.items:type_name -> itemgrpc.Item
	3,  // 4: itemgrpc.ItemService.CreateItem:input_type -> itemgrpc.CreateItemRequest
	5,  // 5: itemgrpc.ItemService.GetItems:input_type -> itemgrpc.GetItemsRequest
	18, // 6: itemgrpc.ItemService.GenerateUniqueItems:input_type -> google.protobuf.Empty
	8,  // 7: itemgrpc.ItemService.UpdateItem:input_type -> itemgrpc.UpdateItemRequest
	10, // 8: itemgrpc.ItemService.CreateRareItem:input_type -> itemgrpc.CreateRareItemRequest
	12, // 9: itemgrpc.ItemService.GetBaseItems:input_type -> itemgrpc.GetBaseItemsRequest
	14, // 10: itemgrpc.ItemService.GetItemMods:input_type -> itemgrpc.GetItemModsRequest
	16, // 11: itemgrpc.ItemService.GetMemberRareItems:input_type -> itemgrpc.GetMemberRareItemsRequest
	4,  // 12: itemgrpc.ItemService.CreateItem:output_type -> itemgrpc.CreateItemResponse
	6,  // 13: itemgrpc.ItemService.GetItems:output_type -> itemgrpc.GetItemsResponse
	7,  // 14: itemgrpc.ItemService.GenerateUniqueItems:output_type -> itemgrpc.GenerateUniqueItemsResponse
	9,  // 15: itemgrpc.ItemService.UpdateItem:output_type -> itemgrpc.UpdateItemResponse
	11, // 16: itemgrpc.ItemService.CreateRareItem:output_type -> itemgrpc.CreateRareItemResponse
	13, // 17: itemgrpc.ItemService.GetBaseItems:output_type -> itemgrpc.GetBaseItemsResponse
	15, // 18: itemgrpc.ItemService.GetItemMods:output_type -> itemgrpc.GetItemModsResponse
	17, // 19: itemgrpc.ItemService.GetMemberRareItems:output_type -> itemgrpc.GetMemberRareItemsResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_item_item_proto_init() }
func file_api_proto_item_item_proto_init() {
	if File_api_proto_item_item_proto != nil {
		return
	}
	file_api_proto_item_item_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_item_item_proto_goTypes,
		DependencyIndexes: file_api_proto_item_item_proto_depIdxs,
		MessageInfos:      file_api_proto_item_item_proto_msgTypes,
	}.Build()
	File_api_proto_item_item_proto = out.File
	file_api_proto_item_item_proto_goTypes = nil
	file_api_proto_item_item_proto_depIdxs = nil
}
