// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/item/item.proto

package itemgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,5,opt,name=imageURL,proto3" json:"imageURL,omitempty"` // repeated Item items = 6;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,5,opt,name=imageURL,proto3" json:"imageURL,omitempty"` // repeated Item items = 6;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{3}
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,5,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetItemsResponse) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *GetItemsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetItemsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetItemsResponse) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type GenerateUniqueItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUniqueItemsResponse) Reset() {
	*x = GenerateUniqueItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUniqueItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUniqueItemsResponse) ProtoMessage() {}

func (x *GenerateUniqueItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUniqueItemsResponse.ProtoReflect.Descriptor instead.
func (*GenerateUniqueItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateUniqueItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_item_item_proto protoreflect.FileDescriptor

const file_api_proto_item_item_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/item/item.proto\x12\bitemgrpc\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\x04Item\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x05 \x01(\tR\bimageURL\"\x89\x01\n" +
	"\x11CreateItemRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x05 \x01(\tR\bimageURL\".\n" +
	"\x12CreateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetItemsRequest\"\x88\x01\n" +
	"\x10GetItemsResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x05 \x01(\tR\bimageURL\"7\n" +
	"\x1bGenerateUniqueItemsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf5\x01\n" +
	"\vItemService\x12I\n" +
	"\n" +
	"CreateItem\x12\x1b.itemgrpc.CreateItemRequest\x1a\x1c.itemgrpc.CreateItemResponse\"\x00\x12C\n" +
	"\bGetItems\x12\x19.itemgrpc.GetItemsRequest\x1a\x1a.itemgrpc.GetItemsResponse\"\x00\x12V\n" +
	"\x13GenerateUniqueItems\x12\x16.google.protobuf.Empty\x1a%.itemgrpc.GenerateUniqueItemsResponse\"\x00B\x12Z\x10./proto;itemgrpcb\x06proto3"

var (
	file_api_proto_item_item_proto_rawDescOnce sync.Once
	file_api_proto_item_item_proto_rawDescData []byte
)

func file_api_proto_item_item_proto_rawDescGZIP() []byte {
	file_api_proto_item_item_proto_rawDescOnce.Do(func() {
		file_api_proto_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)))
	})
	return file_api_proto_item_item_proto_rawDescData
}

var file_api_proto_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_item_item_proto_goTypes = []any{
	(*Item)(nil),                        // 0: itemgrpc.Item
	(*CreateItemRequest)(nil),           // 1: itemgrpc.CreateItemRequest
	(*CreateItemResponse)(nil),          // 2: itemgrpc.CreateItemResponse
	(*GetItemsRequest)(nil),             // 3: itemgrpc.GetItemsRequest
	(*GetItemsResponse)(nil),            // 4: itemgrpc.GetItemsResponse
	(*GenerateUniqueItemsResponse)(nil), // 5: itemgrpc.GenerateUniqueItemsResponse
	(*emptypb.Empty)(nil),               // 6: google.protobuf.Empty
}
var file_api_proto_item_item_proto_depIdxs = []int32{
	1, // 0: itemgrpc.ItemService.CreateItem:input_type -> itemgrpc.CreateItemRequest
	3, // 1: itemgrpc.ItemService.GetItems:input_type -> itemgrpc.GetItemsRequest
	6, // 2: itemgrpc.ItemService.GenerateUniqueItems:input_type -> google.protobuf.Empty
	2, // 3: itemgrpc.ItemService.CreateItem:output_type -> itemgrpc.CreateItemResponse
	4, // 4: itemgrpc.ItemService.GetItems:output_type -> itemgrpc.GetItemsResponse
	5, // 5: itemgrpc.ItemService.GenerateUniqueItems:output_type -> itemgrpc.GenerateUniqueItemsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_item_item_proto_init() }
func file_api_proto_item_item_proto_init() {
	if File_api_proto_item_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_item_item_proto_goTypes,
		DependencyIndexes: file_api_proto_item_item_proto_depIdxs,
		MessageInfos:      file_api_proto_item_item_proto_msgTypes,
	}.Build()
	File_api_proto_item_item_proto = out.File
	file_api_proto_item_item_proto_goTypes = nil
	file_api_proto_item_item_proto_depIdxs = nil
}
