// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/item/item.proto

package itemgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	MemberId    string                 `protobuf:"bytes,2,opt,name=memberId,proto3" json:"memberId,omitempty"`
	BaseItemId  string                 `protobuf:"bytes,3,opt,name=baseItemId,proto3" json:"baseItemId,omitempty"`
	ImageUrl    string                 `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Category    string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Class       string                 `protobuf:"bytes,6,opt,name=class,proto3" json:"class,omitempty"`
	Name        string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Type        string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Description string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	UniqueItem  bool                   `protobuf:"varint,10,opt,name=uniqueItem,proto3" json:"uniqueItem,omitempty"`
	Slot        string                 `protobuf:"bytes,11,opt,name=slot,proto3" json:"slot,omitempty"`
	// armor
	RequiredLevel        *string `protobuf:"bytes,12,opt,name=requiredLevel,proto3,oneof" json:"requiredLevel,omitempty"`
	RequiredStrength     *string `protobuf:"bytes,13,opt,name=requiredStrength,proto3,oneof" json:"requiredStrength,omitempty"`
	RequiredDexterity    *string `protobuf:"bytes,14,opt,name=requiredDexterity,proto3,oneof" json:"requiredDexterity,omitempty"`
	RequiredIntelligence *string `protobuf:"bytes,15,opt,name=requiredIntelligence,proto3,oneof" json:"requiredIntelligence,omitempty"`
	// armor
	Armour       *string `protobuf:"bytes,16,opt,name=armour,proto3,oneof" json:"armour,omitempty"`
	EnergyShield *string `protobuf:"bytes,17,opt,name=energyShield,proto3,oneof" json:"energyShield,omitempty"`
	Evasion      *string `protobuf:"bytes,18,opt,name=evasion,proto3,oneof" json:"evasion,omitempty"`
	Block        *string `protobuf:"bytes,19,opt,name=block,proto3,oneof" json:"block,omitempty"`
	Ward         *string `protobuf:"bytes,20,opt,name=ward,proto3,oneof" json:"ward,omitempty"`
	// weapon
	Damage *string `protobuf:"bytes,21,opt,name=damage,proto3,oneof" json:"damage,omitempty"`
	APS    *string `protobuf:"bytes,22,opt,name=APS,proto3,oneof" json:"APS,omitempty"`
	Crit   *string `protobuf:"bytes,23,opt,name=crit,proto3,oneof" json:"crit,omitempty"`
	PDPS   *string `protobuf:"bytes,24,opt,name=PDPS,proto3,oneof" json:"PDPS,omitempty"`
	EDPS   *string `protobuf:"bytes,25,opt,name=EDPS,proto3,oneof" json:"EDPS,omitempty"`
	DPS    *string `protobuf:"bytes,26,opt,name=DPS,proto3,oneof" json:"DPS,omitempty"`
	// poison
	Life          *string  `protobuf:"bytes,27,opt,name=life,proto3,oneof" json:"life,omitempty"`
	Mana          *string  `protobuf:"bytes,28,opt,name=mana,proto3,oneof" json:"mana,omitempty"`
	Duration      *string  `protobuf:"bytes,29,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Usage         *string  `protobuf:"bytes,30,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	Capacity      *string  `protobuf:"bytes,31,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	Additional    *string  `protobuf:"bytes,32,opt,name=additional,proto3,oneof" json:"additional,omitempty"`
	Implicit      []string `protobuf:"bytes,33,rep,name=implicit,proto3" json:"implicit,omitempty"`
	Stats         []string `protobuf:"bytes,34,rep,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *string  `protobuf:"bytes,36,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	UpdatedAt     *string  `protobuf:"bytes,37,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Item) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Item) GetBaseItemId() string {
	if x != nil {
		return x.BaseItemId
	}
	return ""
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetUniqueItem() bool {
	if x != nil {
		return x.UniqueItem
	}
	return false
}

func (x *Item) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Item) GetRequiredLevel() string {
	if x != nil && x.RequiredLevel != nil {
		return *x.RequiredLevel
	}
	return ""
}

func (x *Item) GetRequiredStrength() string {
	if x != nil && x.RequiredStrength != nil {
		return *x.RequiredStrength
	}
	return ""
}

func (x *Item) GetRequiredDexterity() string {
	if x != nil && x.RequiredDexterity != nil {
		return *x.RequiredDexterity
	}
	return ""
}

func (x *Item) GetRequiredIntelligence() string {
	if x != nil && x.RequiredIntelligence != nil {
		return *x.RequiredIntelligence
	}
	return ""
}

func (x *Item) GetArmour() string {
	if x != nil && x.Armour != nil {
		return *x.Armour
	}
	return ""
}

func (x *Item) GetEnergyShield() string {
	if x != nil && x.EnergyShield != nil {
		return *x.EnergyShield
	}
	return ""
}

func (x *Item) GetEvasion() string {
	if x != nil && x.Evasion != nil {
		return *x.Evasion
	}
	return ""
}

func (x *Item) GetBlock() string {
	if x != nil && x.Block != nil {
		return *x.Block
	}
	return ""
}

func (x *Item) GetWard() string {
	if x != nil && x.Ward != nil {
		return *x.Ward
	}
	return ""
}

func (x *Item) GetDamage() string {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return ""
}

func (x *Item) GetAPS() string {
	if x != nil && x.APS != nil {
		return *x.APS
	}
	return ""
}

func (x *Item) GetCrit() string {
	if x != nil && x.Crit != nil {
		return *x.Crit
	}
	return ""
}

func (x *Item) GetPDPS() string {
	if x != nil && x.PDPS != nil {
		return *x.PDPS
	}
	return ""
}

func (x *Item) GetEDPS() string {
	if x != nil && x.EDPS != nil {
		return *x.EDPS
	}
	return ""
}

func (x *Item) GetDPS() string {
	if x != nil && x.DPS != nil {
		return *x.DPS
	}
	return ""
}

func (x *Item) GetLife() string {
	if x != nil && x.Life != nil {
		return *x.Life
	}
	return ""
}

func (x *Item) GetMana() string {
	if x != nil && x.Mana != nil {
		return *x.Mana
	}
	return ""
}

func (x *Item) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *Item) GetUsage() string {
	if x != nil && x.Usage != nil {
		return *x.Usage
	}
	return ""
}

func (x *Item) GetCapacity() string {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return ""
}

func (x *Item) GetAdditional() string {
	if x != nil && x.Additional != nil {
		return *x.Additional
	}
	return ""
}

func (x *Item) GetImplicit() []string {
	if x != nil {
		return x.Implicit
	}
	return nil
}

func (x *Item) GetStats() []string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Item) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *Item) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"` // repeated Item items = 6;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemsRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // array of items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GenerateUniqueItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUniqueItemsResponse) Reset() {
	*x = GenerateUniqueItemsResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUniqueItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUniqueItemsResponse) ProtoMessage() {}

func (x *GenerateUniqueItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUniqueItemsResponse.ProtoReflect.Descriptor instead.
func (*GenerateUniqueItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateUniqueItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *UpdateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRareItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BaseItemId    string                 `protobuf:"bytes,2,opt,name=baseItemId,proto3" json:"baseItemId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Stats         []string               `protobuf:"bytes,5,rep,name=stats,proto3" json:"stats,omitempty"`
	ToList        bool                   `protobuf:"varint,6,opt,name=toList,proto3" json:"toList,omitempty"` // whether to add the item to the user's item list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRareItemRequest) Reset() {
	*x = CreateRareItemRequest{}
	mi := &file_api_proto_item_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRareItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRareItemRequest) ProtoMessage() {}

func (x *CreateRareItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRareItemRequest.ProtoReflect.Descriptor instead.
func (*CreateRareItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRareItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRareItemRequest) GetBaseItemId() string {
	if x != nil {
		return x.BaseItemId
	}
	return ""
}

func (x *CreateRareItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRareItemRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateRareItemRequest) GetStats() []string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *CreateRareItemRequest) GetToList() bool {
	if x != nil {
		return x.ToList
	}
	return false
}

type CreateRareItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRareItemResponse) Reset() {
	*x = CreateRareItemResponse{}
	mi := &file_api_proto_item_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRareItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRareItemResponse) ProtoMessage() {}

func (x *CreateRareItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_item_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRareItemResponse.ProtoReflect.Descriptor instead.
func (*CreateRareItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_item_item_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRareItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_item_item_proto protoreflect.FileDescriptor

const file_api_proto_item_item_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/item/item.proto\x12\bitemgrpc\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\n" +
	"\n" +
	"\x04Item\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1a\n" +
	"\bmemberId\x18\x02 \x01(\tR\bmemberId\x12\x1e\n" +
	"\n" +
	"baseItemId\x18\x03 \x01(\tR\n" +
	"baseItemId\x12\x1a\n" +
	"\bimageUrl\x18\x04 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x06 \x01(\tR\x05class\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"uniqueItem\x18\n" +
	" \x01(\bR\n" +
	"uniqueItem\x12\x12\n" +
	"\x04slot\x18\v \x01(\tR\x04slot\x12)\n" +
	"\rrequiredLevel\x18\f \x01(\tH\x01R\rrequiredLevel\x88\x01\x01\x12/\n" +
	"\x10requiredStrength\x18\r \x01(\tH\x02R\x10requiredStrength\x88\x01\x01\x121\n" +
	"\x11requiredDexterity\x18\x0e \x01(\tH\x03R\x11requiredDexterity\x88\x01\x01\x127\n" +
	"\x14requiredIntelligence\x18\x0f \x01(\tH\x04R\x14requiredIntelligence\x88\x01\x01\x12\x1b\n" +
	"\x06armour\x18\x10 \x01(\tH\x05R\x06armour\x88\x01\x01\x12'\n" +
	"\fenergyShield\x18\x11 \x01(\tH\x06R\fenergyShield\x88\x01\x01\x12\x1d\n" +
	"\aevasion\x18\x12 \x01(\tH\aR\aevasion\x88\x01\x01\x12\x19\n" +
	"\x05block\x18\x13 \x01(\tH\bR\x05block\x88\x01\x01\x12\x17\n" +
	"\x04ward\x18\x14 \x01(\tH\tR\x04ward\x88\x01\x01\x12\x1b\n" +
	"\x06damage\x18\x15 \x01(\tH\n" +
	"R\x06damage\x88\x01\x01\x12\x15\n" +
	"\x03APS\x18\x16 \x01(\tH\vR\x03APS\x88\x01\x01\x12\x17\n" +
	"\x04crit\x18\x17 \x01(\tH\fR\x04crit\x88\x01\x01\x12\x17\n" +
	"\x04PDPS\x18\x18 \x01(\tH\rR\x04PDPS\x88\x01\x01\x12\x17\n" +
	"\x04EDPS\x18\x19 \x01(\tH\x0eR\x04EDPS\x88\x01\x01\x12\x15\n" +
	"\x03DPS\x18\x1a \x01(\tH\x0fR\x03DPS\x88\x01\x01\x12\x17\n" +
	"\x04life\x18\x1b \x01(\tH\x10R\x04life\x88\x01\x01\x12\x17\n" +
	"\x04mana\x18\x1c \x01(\tH\x11R\x04mana\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x1d \x01(\tH\x12R\bduration\x88\x01\x01\x12\x19\n" +
	"\x05usage\x18\x1e \x01(\tH\x13R\x05usage\x88\x01\x01\x12\x1f\n" +
	"\bcapacity\x18\x1f \x01(\tH\x14R\bcapacity\x88\x01\x01\x12#\n" +
	"\n" +
	"additional\x18  \x01(\tH\x15R\n" +
	"additional\x88\x01\x01\x12\x1a\n" +
	"\bimplicit\x18! \x03(\tR\bimplicit\x12\x14\n" +
	"\x05stats\x18\" \x03(\tR\x05stats\x12!\n" +
	"\tcreatedAt\x18$ \x01(\tH\x16R\tcreatedAt\x88\x01\x01\x12!\n" +
	"\tupdatedAt\x18% \x01(\tH\x17R\tupdatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_requiredLevelB\x13\n" +
	"\x11_requiredStrengthB\x14\n" +
	"\x12_requiredDexterityB\x17\n" +
	"\x15_requiredIntelligenceB\t\n" +
	"\a_armourB\x0f\n" +
	"\r_energyShieldB\n" +
	"\n" +
	"\b_evasionB\b\n" +
	"\x06_blockB\a\n" +
	"\x05_wardB\t\n" +
	"\a_damageB\x06\n" +
	"\x04_APSB\a\n" +
	"\x05_critB\a\n" +
	"\x05_PDPSB\a\n" +
	"\x05_EDPSB\x06\n" +
	"\x04_DPSB\a\n" +
	"\x05_lifeB\a\n" +
	"\x05_manaB\v\n" +
	"\t_durationB\b\n" +
	"\x06_usageB\v\n" +
	"\t_capacityB\r\n" +
	"\v_additionalB\f\n" +
	"\n" +
	"_createdAtB\f\n" +
	"\n" +
	"_updatedAt\"\x99\x01\n" +
	"\x11CreateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\".\n" +
	"\x12CreateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x0fGetItemsRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"R\n" +
	"\x10GetItemsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.itemgrpc.ItemR\x05items\"7\n" +
	"\x1bGenerateUniqueItemsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x99\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\".\n" +
	"\x12UpdateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x15CreateRareItemRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"baseItemId\x18\x02 \x01(\tR\n" +
	"baseItemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x14\n" +
	"\x05stats\x18\x05 \x03(\tR\x05stats\x12\x16\n" +
	"\x06toList\x18\x06 \x01(\bR\x06toList\"2\n" +
	"\x16CreateRareItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x97\x03\n" +
	"\vItemService\x12I\n" +
	"\n" +
	"CreateItem\x12\x1b.itemgrpc.CreateItemRequest\x1a\x1c.itemgrpc.CreateItemResponse\"\x00\x12C\n" +
	"\bGetItems\x12\x19.itemgrpc.GetItemsRequest\x1a\x1a.itemgrpc.GetItemsResponse\"\x00\x12V\n" +
	"\x13GenerateUniqueItems\x12\x16.google.protobuf.Empty\x1a%.itemgrpc.GenerateUniqueItemsResponse\"\x00\x12I\n" +
	"\n" +
	"UpdateItem\x12\x1b.itemgrpc.UpdateItemRequest\x1a\x1c.itemgrpc.UpdateItemResponse\"\x00\x12U\n" +
	"\x0eCreateRareItem\x12\x1f.itemgrpc.CreateRareItemRequest\x1a .itemgrpc.CreateRareItemResponse\"\x00B\x12Z\x10./proto;itemgrpcb\x06proto3"

var (
	file_api_proto_item_item_proto_rawDescOnce sync.Once
	file_api_proto_item_item_proto_rawDescData []byte
)

func file_api_proto_item_item_proto_rawDescGZIP() []byte {
	file_api_proto_item_item_proto_rawDescOnce.Do(func() {
		file_api_proto_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)))
	})
	return file_api_proto_item_item_proto_rawDescData
}

var file_api_proto_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_item_item_proto_goTypes = []any{
	(*Item)(nil),                        // 0: itemgrpc.Item
	(*CreateItemRequest)(nil),           // 1: itemgrpc.CreateItemRequest
	(*CreateItemResponse)(nil),          // 2: itemgrpc.CreateItemResponse
	(*GetItemsRequest)(nil),             // 3: itemgrpc.GetItemsRequest
	(*GetItemsResponse)(nil),            // 4: itemgrpc.GetItemsResponse
	(*GenerateUniqueItemsResponse)(nil), // 5: itemgrpc.GenerateUniqueItemsResponse
	(*UpdateItemRequest)(nil),           // 6: itemgrpc.UpdateItemRequest
	(*UpdateItemResponse)(nil),          // 7: itemgrpc.UpdateItemResponse
	(*CreateRareItemRequest)(nil),       // 8: itemgrpc.CreateRareItemRequest
	(*CreateRareItemResponse)(nil),      // 9: itemgrpc.CreateRareItemResponse
	(*emptypb.Empty)(nil),               // 10: google.protobuf.Empty
}
var file_api_proto_item_item_proto_depIdxs = []int32{
	0,  // 0: itemgrpc.GetItemsResponse.items:type_name -> itemgrpc.Item
	1,  // 1: itemgrpc.ItemService.CreateItem:input_type -> itemgrpc.CreateItemRequest
	3,  // 2: itemgrpc.ItemService.GetItems:input_type -> itemgrpc.GetItemsRequest
	10, // 3: itemgrpc.ItemService.GenerateUniqueItems:input_type -> google.protobuf.Empty
	6,  // 4: itemgrpc.ItemService.UpdateItem:input_type -> itemgrpc.UpdateItemRequest
	8,  // 5: itemgrpc.ItemService.CreateRareItem:input_type -> itemgrpc.CreateRareItemRequest
	2,  // 6: itemgrpc.ItemService.CreateItem:output_type -> itemgrpc.CreateItemResponse
	4,  // 7: itemgrpc.ItemService.GetItems:output_type -> itemgrpc.GetItemsResponse
	5,  // 8: itemgrpc.ItemService.GenerateUniqueItems:output_type -> itemgrpc.GenerateUniqueItemsResponse
	7,  // 9: itemgrpc.ItemService.UpdateItem:output_type -> itemgrpc.UpdateItemResponse
	9,  // 10: itemgrpc.ItemService.CreateRareItem:output_type -> itemgrpc.CreateRareItemResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_item_item_proto_init() }
func file_api_proto_item_item_proto_init() {
	if File_api_proto_item_item_proto != nil {
		return
	}
	file_api_proto_item_item_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_item_item_proto_rawDesc), len(file_api_proto_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_item_item_proto_goTypes,
		DependencyIndexes: file_api_proto_item_item_proto_depIdxs,
		MessageInfos:      file_api_proto_item_item_proto_msgTypes,
	}.Build()
	File_api_proto_item_item_proto = out.File
	file_api_proto_item_item_proto_goTypes = nil
	file_api_proto_item_item_proto_depIdxs = nil
}
