version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: community_builds_build_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community_builds_build_service_db
    ports:
      - "5004:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  test_pgdata:
