// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/cache/cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Time to live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheRequest) Reset() {
	*x = SetCacheRequest{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheRequest) ProtoMessage() {}

func (x *SetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheRequest.ProtoReflect.Descriptor instead.
func (*SetCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCacheRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetCacheRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheResponse) Reset() {
	*x = SetCacheResponse{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheResponse) ProtoMessage() {}

func (x *SetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheResponse.ProtoReflect.Descriptor instead.
func (*SetCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SetCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheRequest) Reset() {
	*x = GetCacheRequest{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheRequest) ProtoMessage() {}

func (x *GetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheRequest.ProtoReflect.Descriptor instead.
func (*GetCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *GetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResponse) Reset() {
	*x = GetCacheResponse{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResponse) ProtoMessage() {}

func (x *GetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResponse.ProtoReflect.Descriptor instead.
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetCacheResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetCacheResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCacheRequest) Reset() {
	*x = DeleteCacheRequest{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCacheRequest) ProtoMessage() {}

func (x *DeleteCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCacheRequest.ProtoReflect.Descriptor instead.
func (*DeleteCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCacheResponse) Reset() {
	*x = DeleteCacheResponse{}
	mi := &file_api_proto_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCacheResponse) ProtoMessage() {}

func (x *DeleteCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCacheResponse.ProtoReflect.Descriptor instead.
func (*DeleteCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_cache_cache_proto protoreflect.FileDescriptor

const file_api_proto_cache_cache_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/cache/cache.proto\x12\tcachegrpc\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"K\n" +
	"\x0fSetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"F\n" +
	"\x10SetCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x0fGetCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"X\n" +
	"\x10GetCacheResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"&\n" +
	"\x12DeleteCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\x13DeleteCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xaa\x02\n" +
	"\fCacheService\x12<\n" +
	"\x05Hello\x12\x17.cachegrpc.HelloRequest\x1a\x18.cachegrpc.HelloResponse\"\x00\x12E\n" +
	"\bSetCache\x12\x1a.cachegrpc.SetCacheRequest\x1a\x1b.cachegrpc.SetCacheResponse\"\x00\x12E\n" +
	"\bGetCache\x12\x1a.cachegrpc.GetCacheRequest\x1a\x1b.cachegrpc.GetCacheResponse\"\x00\x12N\n" +
	"\vDeleteCache\x12\x1d.cachegrpc.DeleteCacheRequest\x1a\x1e.cachegrpc.DeleteCacheResponse\"\x00BNZLgithub.com/darkphotonKN/community-builds-microservice/common/api/proto/cacheb\x06proto3"

var (
	file_api_proto_cache_cache_proto_rawDescOnce sync.Once
	file_api_proto_cache_cache_proto_rawDescData []byte
)

func file_api_proto_cache_cache_proto_rawDescGZIP() []byte {
	file_api_proto_cache_cache_proto_rawDescOnce.Do(func() {
		file_api_proto_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cache_cache_proto_rawDesc), len(file_api_proto_cache_cache_proto_rawDesc)))
	})
	return file_api_proto_cache_cache_proto_rawDescData
}

var file_api_proto_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_cache_cache_proto_goTypes = []any{
	(*HelloRequest)(nil),        // 0: cachegrpc.HelloRequest
	(*HelloResponse)(nil),       // 1: cachegrpc.HelloResponse
	(*SetCacheRequest)(nil),     // 2: cachegrpc.SetCacheRequest
	(*SetCacheResponse)(nil),    // 3: cachegrpc.SetCacheResponse
	(*GetCacheRequest)(nil),     // 4: cachegrpc.GetCacheRequest
	(*GetCacheResponse)(nil),    // 5: cachegrpc.GetCacheResponse
	(*DeleteCacheRequest)(nil),  // 6: cachegrpc.DeleteCacheRequest
	(*DeleteCacheResponse)(nil), // 7: cachegrpc.DeleteCacheResponse
}
var file_api_proto_cache_cache_proto_depIdxs = []int32{
	0, // 0: cachegrpc.CacheService.Hello:input_type -> cachegrpc.HelloRequest
	2, // 1: cachegrpc.CacheService.SetCache:input_type -> cachegrpc.SetCacheRequest
	4, // 2: cachegrpc.CacheService.GetCache:input_type -> cachegrpc.GetCacheRequest
	6, // 3: cachegrpc.CacheService.DeleteCache:input_type -> cachegrpc.DeleteCacheRequest
	1, // 4: cachegrpc.CacheService.Hello:output_type -> cachegrpc.HelloResponse
	3, // 5: cachegrpc.CacheService.SetCache:output_type -> cachegrpc.SetCacheResponse
	5, // 6: cachegrpc.CacheService.GetCache:output_type -> cachegrpc.GetCacheResponse
	7, // 7: cachegrpc.CacheService.DeleteCache:output_type -> cachegrpc.DeleteCacheResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cache_cache_proto_init() }
func file_api_proto_cache_cache_proto_init() {
	if File_api_proto_cache_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cache_cache_proto_rawDesc), len(file_api_proto_cache_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cache_cache_proto_goTypes,
		DependencyIndexes: file_api_proto_cache_cache_proto_depIdxs,
		MessageInfos:      file_api_proto_cache_cache_proto_msgTypes,
	}.Build()
	File_api_proto_cache_cache_proto = out.File
	file_api_proto_cache_cache_proto_goTypes = nil
	file_api_proto_cache_cache_proto_depIdxs = nil
}
