// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Notification        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationsResponse) GetData() []*Notification {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadNotificationResponse) Reset() {
	*x = ReadNotificationResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotificationResponse) ProtoMessage() {}

func (x *ReadNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotificationResponse.ProtoReflect.Descriptor instead.
func (*ReadNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ReadNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Read          bool                   `protobuf:"varint,6,opt,name=read,proto3" json:"read,omitempty"`
	EmailSent     bool                   `protobuf:"varint,7,opt,name=emailSent,proto3" json:"emailSent,omitempty"`
	SourceId      string                 `protobuf:"bytes,8,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetEmailSent() bool {
	if x != nil {
		return x.EmailSent
	}
	return false
}

func (x *Notification) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request message for getting an example by ID
type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetNotificationsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type ReadNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       string                 `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadNotificationRequest) Reset() {
	*x = ReadNotificationRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotificationRequest) ProtoMessage() {}

func (x *ReadNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotificationRequest.ProtoReflect.Descriptor instead.
func (*ReadNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ReadNotificationRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ReadNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

var File_api_proto_notification_notification_proto protoreflect.FileDescriptor

const file_api_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	")api/proto/notification/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x18GetNotificationsResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.notification.NotificationR\x04data\"N\n" +
	"\x18ReadNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmemberId\x18\x02 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04read\x18\x06 \x01(\bR\x04read\x12\x1c\n" +
	"\temailSent\x18\a \x01(\bR\temailSent\x12\x1a\n" +
	"\bsourceId\x18\b \x01(\tR\bsourceId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\x17GetNotificationsRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\tR\bmemberId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"]\n" +
	"\x17ReadNotificationRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\tR\bmemberId\x12&\n" +
	"\x0enotificationId\x18\x02 \x01(\tR\x0enotificationId2\xdf\x01\n" +
	"\x13NotificationService\x12c\n" +
	"\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a&.notification.GetNotificationsResponse\"\x00\x12c\n" +
	"\x10ReadNotification\x12%.notification.ReadNotificationRequest\x1a&.notification.ReadNotificationResponse\"\x00BUZSgithub.com/darkphotonKN/community-builds-microservice/common/api/proto/notificationb\x06proto3"

var (
	file_api_proto_notification_notification_proto_rawDescOnce sync.Once
	file_api_proto_notification_notification_proto_rawDescData []byte
)

func file_api_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_api_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_api_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)))
	})
	return file_api_proto_notification_notification_proto_rawDescData
}

var file_api_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_notification_notification_proto_goTypes = []any{
	(*GetNotificationsResponse)(nil), // 0: notification.GetNotificationsResponse
	(*ReadNotificationResponse)(nil), // 1: notification.ReadNotificationResponse
	(*Notification)(nil),             // 2: notification.Notification
	(*GetNotificationsRequest)(nil),  // 3: notification.GetNotificationsRequest
	(*ReadNotificationRequest)(nil),  // 4: notification.ReadNotificationRequest
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_api_proto_notification_notification_proto_depIdxs = []int32{
	2, // 0: notification.GetNotificationsResponse.data:type_name -> notification.Notification
	5, // 1: notification.Notification.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: notification.NotificationService.GetNotifications:input_type -> notification.GetNotificationsRequest
	4, // 3: notification.NotificationService.ReadNotification:input_type -> notification.ReadNotificationRequest
	0, // 4: notification.NotificationService.GetNotifications:output_type -> notification.GetNotificationsResponse
	1, // 5: notification.NotificationService.ReadNotification:output_type -> notification.ReadNotificationResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_notification_notification_proto_init() }
func file_api_proto_notification_notification_proto_init() {
	if File_api_proto_notification_notification_proto != nil {
		return
	}
	file_api_proto_notification_notification_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_api_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_api_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_api_proto_notification_notification_proto = out.File
	file_api_proto_notification_notification_proto_goTypes = nil
	file_api_proto_notification_notification_proto_depIdxs = nil
}
