// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/skill/skill.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Skill) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Skill) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillResponse) Reset() {
	*x = CreateSkillResponse{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponse) ProtoMessage() {}

func (x *CreateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{2}
}

type GetSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillsRequest) Reset() {
	*x = GetSkillsRequest{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillsRequest) ProtoMessage() {}

func (x *GetSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillsRequest.ProtoReflect.Descriptor instead.
func (*GetSkillsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{3}
}

type GetSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillsResponse) Reset() {
	*x = GetSkillsResponse{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillsResponse) ProtoMessage() {}

func (x *GetSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillsResponse.ProtoReflect.Descriptor instead.
func (*GetSkillsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

var File_api_proto_skill_skill_proto protoreflect.FileDescriptor

const file_api_proto_skill_skill_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/skill/skill.proto\x12\x05skill\"{\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"X\n" +
	"\x12CreateSkillRequest\x12\x1a\n" +
	"\bMemberId\x18\x01 \x01(\tR\bMemberId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\x15\n" +
	"\x13CreateSkillResponse\"\x12\n" +
	"\x10GetSkillsRequest\"9\n" +
	"\x11GetSkillsResponse\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.skill.SkillR\x06skills2\x98\x01\n" +
	"\fSkillService\x12F\n" +
	"\vCreateSkill\x12\x19.skill.CreateSkillRequest\x1a\x1a.skill.CreateSkillResponse\"\x00\x12@\n" +
	"\tGetSkills\x12\x17.skill.GetSkillsRequest\x1a\x18.skill.GetSkillsResponse\"\x00BOZMgithub.com/darkphotonKN/community-builds-microservices/common/api/proto/skillb\x06proto3"

var (
	file_api_proto_skill_skill_proto_rawDescOnce sync.Once
	file_api_proto_skill_skill_proto_rawDescData []byte
)

func file_api_proto_skill_skill_proto_rawDescGZIP() []byte {
	file_api_proto_skill_skill_proto_rawDescOnce.Do(func() {
		file_api_proto_skill_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_skill_skill_proto_rawDesc), len(file_api_proto_skill_skill_proto_rawDesc)))
	})
	return file_api_proto_skill_skill_proto_rawDescData
}

var file_api_proto_skill_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_skill_skill_proto_goTypes = []any{
	(*Skill)(nil),               // 0: skill.Skill
	(*CreateSkillRequest)(nil),  // 1: skill.CreateSkillRequest
	(*CreateSkillResponse)(nil), // 2: skill.CreateSkillResponse
	(*GetSkillsRequest)(nil),    // 3: skill.GetSkillsRequest
	(*GetSkillsResponse)(nil),   // 4: skill.GetSkillsResponse
}
var file_api_proto_skill_skill_proto_depIdxs = []int32{
	0, // 0: skill.GetSkillsResponse.skills:type_name -> skill.Skill
	1, // 1: skill.SkillService.CreateSkill:input_type -> skill.CreateSkillRequest
	3, // 2: skill.SkillService.GetSkills:input_type -> skill.GetSkillsRequest
	2, // 3: skill.SkillService.CreateSkill:output_type -> skill.CreateSkillResponse
	4, // 4: skill.SkillService.GetSkills:output_type -> skill.GetSkillsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_skill_skill_proto_init() }
func file_api_proto_skill_skill_proto_init() {
	if File_api_proto_skill_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_skill_skill_proto_rawDesc), len(file_api_proto_skill_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_skill_skill_proto_goTypes,
		DependencyIndexes: file_api_proto_skill_skill_proto_depIdxs,
		MessageInfos:      file_api_proto_skill_skill_proto_msgTypes,
	}.Build()
	File_api_proto_skill_skill_proto = out.File
	file_api_proto_skill_skill_proto_goTypes = nil
	file_api_proto_skill_skill_proto_depIdxs = nil
}
