// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/skill/skill.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillResponse) Reset() {
	*x = CreateSkillResponse{}
	mi := &file_api_proto_skill_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponse) ProtoMessage() {}

func (x *CreateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_skill_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_skill_skill_proto_rawDescGZIP(), []int{1}
}

var File_api_proto_skill_skill_proto protoreflect.FileDescriptor

const file_api_proto_skill_skill_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/skill/skill.proto\x12\x05skill\"<\n" +
	"\x12CreateSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x15\n" +
	"\x13CreateSkillResponse2V\n" +
	"\fSkillService\x12F\n" +
	"\vCreateSkill\x12\x19.skill.CreateSkillRequest\x1a\x1a.skill.CreateSkillResponse\"\x00BOZMgithub.com/darkphotonKN/community-builds-microservices/common/api/proto/skillb\x06proto3"

var (
	file_api_proto_skill_skill_proto_rawDescOnce sync.Once
	file_api_proto_skill_skill_proto_rawDescData []byte
)

func file_api_proto_skill_skill_proto_rawDescGZIP() []byte {
	file_api_proto_skill_skill_proto_rawDescOnce.Do(func() {
		file_api_proto_skill_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_skill_skill_proto_rawDesc), len(file_api_proto_skill_skill_proto_rawDesc)))
	})
	return file_api_proto_skill_skill_proto_rawDescData
}

var file_api_proto_skill_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_skill_skill_proto_goTypes = []any{
	(*CreateSkillRequest)(nil),  // 0: skill.CreateSkillRequest
	(*CreateSkillResponse)(nil), // 1: skill.CreateSkillResponse
}
var file_api_proto_skill_skill_proto_depIdxs = []int32{
	0, // 0: skill.SkillService.CreateSkill:input_type -> skill.CreateSkillRequest
	1, // 1: skill.SkillService.CreateSkill:output_type -> skill.CreateSkillResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_skill_skill_proto_init() }
func file_api_proto_skill_skill_proto_init() {
	if File_api_proto_skill_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_skill_skill_proto_rawDesc), len(file_api_proto_skill_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_skill_skill_proto_goTypes,
		DependencyIndexes: file_api_proto_skill_skill_proto_depIdxs,
		MessageInfos:      file_api_proto_skill_skill_proto_msgTypes,
	}.Build()
	File_api_proto_skill_skill_proto = out.File
	file_api_proto_skill_skill_proto_goTypes = nil
	file_api_proto_skill_skill_proto_depIdxs = nil
}
