gen:
	@protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
		api/proto/common/common.proto \
		api/proto/example/example.proto \
		api/proto/item/item.proto \
