// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	MemberId      string                 `protobuf:"bytes,4,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomerRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCustomerResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_api_proto_payment_payment_proto protoreflect.FileDescriptor

const file_api_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/payment/payment.proto\x12\apayment\"\x99\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x03R\x05Price\x12\x1a\n" +
	"\bMemberId\x18\x04 \x01(\tR\bMemberId\x12\x14\n" +
	"\x05Email\x18\x05 \x01(\tR\x05Email\"\x1c\n" +
	"\x1aCreateSubscriptionResponse\"I\n" +
	"\x15CreateCustomerRequest\x12\x1a\n" +
	"\bMemberId\x18\x01 \x01(\tR\bMemberId\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\"8\n" +
	"\x16CreateCustomerResponse\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x01 \x01(\tR\n" +
	"CustomerId2\xc6\x01\n" +
	"\x0ePaymentService\x12_\n" +
	"\x12CreateSubscription\x12\".payment.CreateSubscriptionRequest\x1a#.payment.CreateSubscriptionResponse\"\x00\x12S\n" +
	"\x0eCreateCustomer\x12\x1e.payment.CreateCustomerRequest\x1a\x1f.payment.CreateCustomerResponse\"\x00BQZOgithub.com/darkphotonKN/community-builds-microservices/common/api/proto/paymentb\x06proto3"

var (
	file_api_proto_payment_payment_proto_rawDescOnce sync.Once
	file_api_proto_payment_payment_proto_rawDescData []byte
)

func file_api_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_api_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)))
	})
	return file_api_proto_payment_payment_proto_rawDescData
}

var file_api_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_payment_payment_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil),  // 0: payment.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 1: payment.CreateSubscriptionResponse
	(*CreateCustomerRequest)(nil),      // 2: payment.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),     // 3: payment.CreateCustomerResponse
}
var file_api_proto_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.CreateSubscription:input_type -> payment.CreateSubscriptionRequest
	2, // 1: payment.PaymentService.CreateCustomer:input_type -> payment.CreateCustomerRequest
	1, // 2: payment.PaymentService.CreateSubscription:output_type -> payment.CreateSubscriptionResponse
	3, // 3: payment.PaymentService.CreateCustomer:output_type -> payment.CreateCustomerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_payment_payment_proto_init() }
func file_api_proto_payment_payment_proto_init() {
	if File_api_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_api_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_api_proto_payment_payment_proto = out.File
	file_api_proto_payment_payment_proto_goTypes = nil
	file_api_proto_payment_payment_proto_depIdxs = nil
}
